[project]
name = "b2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "httpx>=0.24.1",
    "pandas>=1.1.5",
    "pyarrow>=12.0.1",
]
